#!/usr/bin/env ruby

require_relative "prelude"

CONFIG_FILE = "#{Dir.home}/.dotfiles/config/brittany/config.yaml"

def in_global_project?
  `stack path | grep "project-root"`
    .include?('.dotfiles/stack/global-project')
end

def targets
  `find . -name '*.hs' | grep -v '.stack-work'`
    .lines
    .map { |x| x.strip }
end

def main
  ensure_bin("stack")
  ensure_bin("brittany")
  ensure_args(0)
  panic("Not in a stack project.") if in_global_project?
  panic("No target found.") if targets.size == 0
  `brittany --config-file #{CONFIG_FILE} --write-mode=inplace #{targets.join(' ')}`
end

main
