#!/usr/bin/env ruby

require_relative "prelude"

def in_global_project?
  `stack path | grep "project-root"`
    .include?('.dotfiles/stack/global-project')
end

def targets
  `find . -name '*.hs' | grep -v '.stack-work'`
    .lines
    .map { |x| x.strip }
end

def main
  ensure_bin("stack")
  ensure_bin("ormolu")
  ensure_args(0)
  panic("Not in a stack project.") if in_global_project?
  panic("No target found.") if targets.size == 0
  `ormolu --mode inplace #{targets.join(' ')}`
end

main
